# Site settings
title:          Waffle Blog
description:    "Waffles can not be beaten. Fuck you, Pancakes."
url:            https://blog.waffledev.tech

# Author
author:
  name:         Waffle
  email:        yo@waffledev.tech
  url:          https://blog.waffledev.tech

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: yo@waffledev.tech
